name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get PNPM store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup PNPM cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Create env file
        run: |
          echo "NEXT_PUBLIC_API_URL=https://e-helpdesk-back-r1nabbk9f-richard-blackers-projects.vercel.app/" > .env.local
      - name: Build with Next.js
        run: pnpm build
      - name: List output directory contents (debug)
        run: |
          if [ -d "out" ]; then
            echo "Contents of out directory:"
            ls -la out/
          else
            echo "out directory does not exist"
            echo "Checking dist directory:"
            ls -la dist/ || echo "dist directory does not exist"
          fi
      - name: Check for important files
        run: |
          # Check and copy 404.html
          if [ -f "out/404.html" ]; then
            echo "404.html exists in out directory"
          else 
            echo "404.html not found in out directory, copying from public"
            cp public/404.html out/ || echo "Failed to copy 404.html"
          fi
          
          # Check if index.html exists in the base directory
          if [ -f "out/index.html" ]; then
            echo "index.html exists in out directory"
          else
            echo "index.html not found in out directory"
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4